---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 515219404-HLYyMRMZc0J6HufYLYoVh4LLm9ZUeoIDboePaeot
:access_token_secret: g9bufi0vvcI0L9nMGTlUEFPEV7pHU38zsJaF2Q97ysTST
